version: "3.3"

services:
  db:
    build:
      context: .
      dockerfile: ./docker/amd64/Dockerfile.takserver-db
    volumes:
      - "db_data:/var/lib/postgresql/data:z"
      - "./tak:/opt/tak:z"
    networks:
      tak:
        aliases:
          - tak-database
    ports:
      - "172.16.0.2:5432:5432"
    restart: unless-stopped

  tak:
    build:
      context: .
      dockerfile: ./docker/amd64/Dockerfile.takserver
    env_file:
      - .env
    volumes:
      - "./tak:/opt/tak:z"
    ports:
      - "172.16.0.2:8443:8443"
      - "172.16.0.2:8444:8444"
      - "172.16.0.2:8446:8446"
      - "172.16.0.2:8089:8089"
      - "172.16.0.2:9000:9000"
      - "172.16.0.2:9001:9001"
    networks:
      tak:
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:

networks:
  tak:
